# Generated by Django 3.2.21 on 2024-01-08 06:55

from django.db import migrations, models
import django.db.models.deletion


def populate_categoria(apps, schema_editor):
    Categoria = apps.get_model('api', 'Categoria')

    categorias = [
        ('Informática'),
        ('Celulares'),
        ('Beleza e Perfumaria'),
        ('Mercado'),
        ('Livros e Papelaria'),
        ('Brinquedos'),
        ('Moda'),
        ('Bebê'),
        ('Games')
    ]

    for descricao in categorias:
        Categoria.objects.create(descricao=descricao)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),

        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.IntegerField(unique=True)),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('valor', models.FloatField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),

        migrations.RunPython(populate_categoria)
    ]
