# Generated by Django 4.2.1 on 2024-01-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clientes_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.CharField(max_length=55),
        ),
    ]
