# Generated by Django 4.2.1 on 2024-01-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clientes_cpf_alter_clientes_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('valor_total', models.FloatField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.IntegerField()),
                ('valor_produto', models.FloatField()),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedidos')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtos')),
            ],
        ),
    ]
