# Generated by Django 4.2.1 on 2024-01-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pedidos_pedidosprodutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosprodutos',
            name='pedido_id',
        ),
    ]
